import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavbarHeader from "./components/NavbarHeader";
import NavbarFooter from "./components/NavbarFooter";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className}
        antialiased
        overflow-y-scroll
        bg-[url('/background.webp')]
        bg-cover
        bg-no-repeat
        bg-fixed
        bg-top
      `}
      >
        <div className="max-w-[780px] p-4 md:p-10 mx-auto bg-background min-h-screen">
          <NavbarHeader />
          {children}
          <NavbarFooter />
        </div>
      </body>
    </html>
  );
}
